# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-11 01:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data_DB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_en', models.TextField(blank=True, null=True)),
                ('text_sp', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=140)),
                ('title_sp', models.CharField(max_length=140)),
                ('slug_sp', models.CharField(max_length=140)),
                ('slug_en', models.CharField(max_length=140)),
                ('in_main_menu', models.BooleanField(default=False)),
                ('in_footer', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='data_db',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Section'),
        ),
    ]
